language: generic
os:
- linux
- osx
env:
  matrix:
  - CONDA_ENV=3.7
  - CONDA_ENV=3.8
  global:
    secure: aY9Vw07d+nv+vfoKvsR+DX9L3lSeAiS+6EHKiXmqZBtXntnhJsz8TXNYX2gSXd+cc81wKgli59iAcpwC8KgPuSf9oYZwPA/DT4o7ww8UdHKV7IFNYpBJtamfOps9Lx/LINNz55nuzI23k4XA5s8hj4y5c5BckQc/0nSoDz+2tYb7HnN8pgFnhG3quOi6z9/xj46+NfkOp+ITE3Y3QmBz3EPHUFeQxf567JbYByCXpOkGgm/qu6y67yy4oR1zMZBKjIPmg6Oxl8syv48xTKsr08OOyIjU8JFsLwc3r3cJB19H1ORxwNcWlEtgDD7Mu+BID5JIPoQKG+WhahEgTlac2nIIYTK0g/ZopwUM/9RVgexnfz/ddV8+1Oz5LjtXS+pzs2CNdo0wGzKAGofVbYltrkIWQrhK3wwRp4UixS9odc8t+/l2QI6F3AGhkuKUimzE3yGAkaEfPwCWK9Axci9B6Elnj8qzu2/vdh6k6CAAimrIhslLvpJYfbZG+36pBAS1woBHJtNujRrosatiVoo0U3GgLb9BE5zOkmJ7q74zclWMji0FiiDaEnkYUdw1ddncUB3af9GlsiZ/6SJRTzmf/oSPkYtIvShQRvQffds/sKgajrILIAuO/XtmwCaGILsfzq5Pq93F6aVihB3fb3KYTuaqPjy5ZhhqQllIAGyeqq8=
jobs:
  include:
  - stage: lint
    os: linux
    script:
    - pip install flake8
    - make lint
  - stage: deploy
    if: tag =~ v.*$
    os: osx
    env: CONDA_ENV=3.7
    script:
    - pip install twine wheel
    - python setup.py bdist_wheel
    - twine upload -u gantian127 -p$PYPI_PASS dist/*nwm*
before_install:
- |
  if [[ $TRAVIS_OS_NAME == "osx" ]]; then
    brew remove --force $(brew list)
    brew cleanup -s
    rm -rf $(brew --cache)
  fi
- |
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    curl https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh > $HOME/miniconda.sh
  else
    curl https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh > $HOME/miniconda.sh
  fi
- bash $HOME/miniconda.sh -b -p $(pwd)/anaconda
- export PATH="$(pwd)/anaconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda create -n test_env python=$CONDA_ENV
- source activate test_env
- conda info -a && conda list
install:
- pip install -e .
script:
- pip install pytest pytest-cov pytest-datadir coveralls
- pytest --cov=nwm --cov-report=xml:$(pwd)/coverage.xml -vvv
after_success: coveralls